### ISSUE TITLE
Should `Program` automatically re-define existing definitions instead of allowing duplicates?

### ISSUE THREAD

**Issue by MarquessV** [rigetti/quil-rs#224]
In `pyQuil`, when adding something like a `DefGate` or `DefCalibration` to a `Program`, it checks if the identifier has an existing definition first. If it exists, it replaces the existing definition with the new one. This is in contrast to `quil-rs`, which will always just add it to the program, which can lead to multiple definitions for the same identifier.

Should `quil-rs` mirror pyQuil's behavior here, or do we chalk it up to user error? To implement, we'd need to refactor `CalibrationSet` and `FrameSet` to behave like sets, with appropriate data types. We'd also need a new field to efficiently manage what gate definitions exist in the program.

**Comment by MarquessV** [comment]
The Quil spec doesn't state that multiple definitions of a `DEFGATE` or `DEFCAL` is invalid. `quilc` and `QVM` also both support duplicate `DEFGATE` definitions, so allowing it errs more on the side of representing Quil faithfully, but could be an inconvenience for downstream users.

**Comment by MarquessV** [comment]
Since the Quil spec considers this valid, we are not going to implement this as part of quil-rs.

**Comment by bramathon** [comment]
I would add that the performance concern is much more significant than I had previously realized. In this direction we have discussed the addition of a method that would actually remove unused definitions in order to reduce serialization overhead.

One additional comment is that retrieving definitions for instructions is a common task that would be considerably easier and faster if they were stored as a dictionary. Some definitions (eg frames) already are while others are not.
