### ISSUE TITLE
Improve Error Messages

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rs#51]
Currently, parsing errors look like this:

```
Error("InvalidCommand { command: DefCal, error: \"Parsing Error: ExpectedToken { actual: Colon, expected: \\\"Identifier\\\" } (at Colon)\" } (at Command(DefCal))")'
```

What caused this: `DEFCAL MEASURE 0:` should have been `DEFCAL MEASURE 0 addr:`.

Not great. With in-depth knowledge of the parser and a simple program, this is actionable information. However, with program lengths in the hundreds of lines or more, and without personal experience with this library, this is almost useless. Further, given that this library is under rapid development, there are still plenty of bugs, and that there are inconsistencies within the Quil spec itself, this can cause a jarring experience to someone who submits a valid program but cannot parse it.

Error messages should:

1. Include the line number within the input string at which the error was encountered. Bonus points for index within the line, if that comes as a package deal.
2. Display the readable string version of the offending instruction, not the debug version
3. Include a clear error message explaining what failed in lexing or parsing.

**Comment by nilslice** [comment]
Agree with all of the above. Additionally, I'd like to consider how these errors bubble up to other tools and will be presented in contexts outside direct use of this crate. 

Driving this consideration is the assumption that it will be less likely for users to interact with this crate, and more likely that it returns errors to some dependent program. 

If that's true, it's probably worthwhile to draw a line at this crate by introducing some new state for the error, and some abstraction to "present" it vs. directly printing out errors in some opinionated way. 

I'd also like to (now or eventually) support a way to plumb through some verbosity indicator, so that users of the library in code, or via dependent tools can enable diagnostics / feedback about the program & how it is parsed. Not sure what this looks like yet, but it's in the same realm as error message improvement so I figured I'd bring it up!

**Comment by genos** [comment]
Haven't used it much myself, but the error & diagnostic reporting in [`miette`](https://docs.rs/miette/latest/miette/) seems really nice.

**Comment by dbanty** [comment]
Agreed @genos, I think `miette` will be ideal for this because we can show the area of the input source which had the error (assuming we can keep track of position while we parse).
